import React, { useState, useEffect, useCallback } from 'react';
import Head from 'next/head';
import Link from 'next/link';

// ─── Constants ─────────────────────────────────────────────────────────────────
// Public, PII-free casting feed generated by CastingNotify and served directly from Blob storage.
// The feed is the dashboard MODEL shape: { generated_at, last_run, new_count, counts,
// bucket_order, bucket_label, health, groups:{ bucket: [card, ...] } }. Cards are already
// grouped server-side and pared down (public fields only, score tag dropped, URLs verbatim).
const API_URL = 'https://stcngwebf9edd8.blob.core.windows.net/castingnotify-web/feed.json';

// Fixed, allowlisted buckets — sections/classes are NEVER derived from arbitrary feed values.
const SECTIONS = [
    { bucket: 'strong', label: 'Strong matches', accent: 'border-green-500', dot: 'bg-green-500' },
    { bucket: 'union_caution', label: 'Union — worth a look (Taft-Hartley)', accent: 'border-purple-500', dot: 'bg-purple-500' },
    { bucket: 'possible', label: 'Possible', accent: 'border-amber-500', dot: 'bg-amber-500' },
    { bucket: 'age_unclear', label: 'Age unclear', accent: 'border-orange-500', dot: 'bg-orange-500', hideWhenEmpty: true }
];

// Map the server-computed tag CSS class to a Tailwind pill. The feed owns tag content (the
// internal "score" tag is already removed server-side); we render text verbatim and only style.
const TAG_CLASS = {
    tag: 'bg-gray-100 text-gray-600',
    'tag new': 'bg-green-600 text-white',
    'tag dist': 'bg-blue-50 text-blue-700',
    'tag union': 'bg-purple-100 text-purple-700',
    'tag review': 'bg-yellow-100 text-yellow-800',
    'tag llm-adult': 'bg-red-100 text-red-700',
    'tag llm-youth': 'bg-green-100 text-green-700'
};

// ─── Utility helpers ──────────────────────────────────────────────────────────
// Only allow absolute http/https URLs with no embedded credentials (defense-in-depth; the
// server already host/scheme-validates, but the SPA re-validates everything it renders).
function safeUrl(raw) {
    if (!raw || typeof raw !== 'string') return null;
    try {
        const u = new URL(raw);
        if (u.protocol !== 'http:' && u.protocol !== 'https:') return null;
        if (u.username || u.password) return null;
        return u;
    } catch (e) {
        return null;
    }
}

function timeAgo(iso) {
    const t = Date.parse(iso);
    if (isNaN(t)) return '';
    const s = Math.max(0, Math.floor((Date.now() - t) / 1000));
    if (s < 90) return 'just now';
    const m = Math.floor(s / 60);
    if (m < 60) return `${m} min ago`;
    const h = Math.floor(m / 60);
    if (h < 24) return `${h} ${h === 1 ? 'hour' : 'hours'} ago`;
    const d = Math.floor(h / 24);
    return `${d} ${d === 1 ? 'day' : 'days'} ago`;
}

function Card({ card }) {
    const tags = Array.isArray(card.tags) ? card.tags.filter((t) => t && t.text) : [];

    // Roles: prefer the LLM's youth-role reading; fall back to the parsed roles (filtering out the
    // internal "(listing)" placeholder sentinel). Hide the whole box when neither has content.
    const youthRoles = Array.isArray(card.llm_youth_roles)
        ? card.llm_youth_roles.filter((r) => r && r.name)
        : [];
    const parsedRoles = Array.isArray(card.roles)
        ? card.roles.filter((r) => r && r !== '(listing)')
        : [];
    const useYouth = youthRoles.length > 0;
    const showRoles = useYouth || parsedRoles.length > 0;

    // Links: validate + dedupe each URL client-side; render one anchor per distinct listing.
    const seen = new Set();
    const links = [];
    (Array.isArray(card.urls) ? card.urls : []).forEach((raw) => {
        const u = safeUrl(raw);
        if (u && !seen.has(u.href)) {
            seen.add(u.href);
            links.push(u);
        }
    });
    const sources = Array.isArray(card.source_labels) ? card.source_labels.filter(Boolean) : [];

    return (
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-4">
            <h3 className="text-base font-semibold text-gray-900">
                {card.title || 'Untitled'}
                {card.org ? <span className="font-normal text-gray-500"> · {card.org}</span> : null}
            </h3>

            {tags.length ? (
                <div className="flex flex-wrap gap-1.5 mt-2">
                    {tags.map((t, i) => (
                        <span
                            key={i}
                            className={`text-xs px-2 py-0.5 rounded ${TAG_CLASS[t.cls] || TAG_CLASS.tag}`}
                        >
                            {t.text}
                        </span>
                    ))}
                </div>
            ) : null}

            {card.llm_summary ? <div className="text-sm text-gray-600 mt-2">{card.llm_summary}</div> : null}

            {card.eligibility_note ? (
                <div className="text-sm text-gray-500 mt-2">{card.eligibility_note}</div>
            ) : null}
            {card.future_round_note ? (
                <div className="mt-2">
                    <span className="inline-block rounded bg-purple-100 px-2 py-1 text-sm font-semibold text-purple-700">
                        📣 {card.future_round_note}
                    </span>
                </div>
            ) : null}

            {showRoles ? (
                <div className="mt-2 rounded-md border border-gray-200 bg-gray-50 px-3 py-2">
                    <div className="text-xs font-semibold uppercase tracking-wide text-gray-700">Roles</div>
                    <ul className="list-disc pl-5 text-sm text-gray-700 mt-1">
                        {useYouth
                            ? youthRoles.map((r, i) => (
                                  <li key={i}>
                                      {r.name}
                                      {r.quote ? (
                                          <span className="italic text-gray-500"> — “{r.quote}”</span>
                                      ) : null}
                                  </li>
                              ))
                            : parsedRoles.map((r, i) => <li key={i}>{r}</li>)}
                    </ul>
                </div>
            ) : null}

            {card.description ? <div className="text-sm text-gray-600 mt-2">{card.description}</div> : null}

            {links.length || sources.length ? (
                <div className="mt-2 text-sm flex flex-wrap items-center gap-x-3 gap-y-1">
                    {links.map((u, i) => (
                        <a
                            key={i}
                            href={u.href}
                            target="_blank"
                            rel="noopener noreferrer"
                            referrerPolicy="no-referrer"
                            className="text-purple-600 hover:underline font-medium"
                        >
                            open original ↗ <span className="text-xs text-gray-400 font-normal">{u.hostname}</span>
                        </a>
                    ))}
                    {sources.length ? (
                        <span className="text-xs text-gray-400">via {sources.join(', ')}</span>
                    ) : null}
                </div>
            ) : null}
        </div>
    );
}

export default function Casting() {
    const [feed, setFeed] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [notReady, setNotReady] = useState(false);

    const fetchData = useCallback(async () => {
        setLoading(true);
        setError(null);
        setNotReady(false);
        try {
            const res = await fetch(API_URL, { method: 'GET', credentials: 'omit' });
            if (res.status === 404) {
                setNotReady(true);
                setFeed(null);
                setError(null);
                return;
            }
            if (!res.ok) throw new Error(`HTTP ${res.status}`);
            const data = await res.json();
            setFeed(data);
            setNotReady(false);
            setError(null);
        } catch (e) {
            setError('Couldn’t load opportunities right now. Please try again later.');
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => {
        fetchData();
    }, [fetchData]);

    // Read the server-grouped model defensively: only allowlisted buckets, each a list of cards.
    const groups =
        feed && feed.groups && typeof feed.groups === 'object' && !Array.isArray(feed.groups)
            ? feed.groups
            : {};
    const byBucket = {};
    SECTIONS.forEach((s) => {
        byBucket[s.bucket] = Array.isArray(groups[s.bucket]) ? groups[s.bucket].filter(Boolean) : [];
    });
    const updated = feed ? timeAgo(feed.generated_at) : '';
    const shownCount = SECTIONS.reduce((n, s) => n + byBucket[s.bucket].length, 0);

    const cardKey = (card, i) =>
        `${card.bucket || ''}|${card.title || ''}|${card.first_seen || ''}|${(Array.isArray(card.urls) && card.urls[0]) || i}`;

    return (
        <>
            <Head>
                <title>Casting opportunities — Sage</title>
                <meta name="description" content="Current youth casting and audition opportunities for Sage." />
                <meta name="robots" content="noindex" />
            </Head>

            <header className="bg-white border-b border-gray-200 sticky top-0 z-10 shadow-sm">
                <div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between">
                    <nav className="flex items-center gap-5">
                        <Link href="/" className="text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors">
                            Home
                        </Link>
                        <Link href="/blog" className="text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors">
                            Blog
                        </Link>
                        <Link href="/about" className="text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors">
                            About
                        </Link>
                        <span className="text-sm font-bold text-purple-700">🎭 Casting</span>
                    </nav>
                    <button
                        onClick={fetchData}
                        title="Refresh"
                        className="w-8 h-8 flex items-center justify-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-100 hover:text-gray-800 transition-colors text-base"
                    >
                        ↻
                    </button>
                </div>
            </header>

            <main className="bg-gray-50 min-h-screen">
                <div className="max-w-5xl mx-auto px-4 py-8">
                    <div className="mb-6">
                        <h1 className="text-3xl font-bold text-gray-900 mb-1">🎭 Casting opportunities</h1>
                        <p className="text-gray-500 text-sm">
                            Auditions and youth-development calls, aggregated automatically.
                            {feed ? ` Updated ${updated || 'recently'} · ${shownCount} opportunities.` : ''}
                        </p>
                    </div>

                    {loading && !feed && !notReady && !error ? (
                        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-16 text-center">
                            <div className="text-gray-400 text-lg animate-pulse">Loading opportunities…</div>
                        </div>
                    ) : null}

                    {notReady ? (
                        <div className="bg-white rounded-xl border border-amber-200 shadow-sm p-10 text-center">
                            <div className="text-amber-700 font-medium">The feed isn’t published yet — check back soon.</div>
                        </div>
                    ) : null}

                    {error ? (
                        <div className="bg-white rounded-xl border border-red-200 shadow-sm p-10 text-center">
                            <div className="text-red-500 font-medium mb-3">{error}</div>
                            <button onClick={fetchData} className="text-sm text-purple-600 hover:underline">
                                Try again
                            </button>
                        </div>
                    ) : null}

                    {feed && !error
                        ? SECTIONS.filter((s) => !s.hideWhenEmpty || byBucket[s.bucket].length > 0).map((s) => (
                              <section key={s.bucket} className="mb-8">
                                  <h2 className={`flex items-center gap-2 text-lg font-semibold text-gray-900 border-b-2 ${s.accent} pb-1 mb-3`}>
                                      <span className={`inline-block w-2.5 h-2.5 rounded-full ${s.dot}`} />
                                      {s.label} ({byBucket[s.bucket].length})
                                  </h2>
                                  {byBucket[s.bucket].length === 0 ? (
                                      <p className="text-sm text-gray-400 italic">None right now.</p>
                                  ) : (
                                      <div className="grid gap-3">
                                          {byBucket[s.bucket].map((c, i) => (
                                              <Card key={cardKey(c, i)} card={c} />
                                          ))}
                                      </div>
                                  )}
                              </section>
                          ))
                        : null}

                    <footer className="text-xs text-gray-400 mt-10">
                        Listings are aggregated automatically; always confirm details on the original listing.
                        This page shows no personal information.
                    </footer>
                </div>
            </main>
        </>
    );
}
